# Generated by Django 4.0.4 on 2022-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
